# Generated by Django 5.2.17 on 2026-09-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    """Drop the invitation-code registration flow: registration is now self-service,
    with the role chosen directly by the applicant (see accounts.views.RegisterStartView)."""

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingregistration',
            name='invite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invite_code',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='invite_checked_at',
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='role',
            field=models.CharField(choices=[('admin', 'Notaire · Admin'), ('clerc', 'Clerc principal'), ('collaborateur', 'Collaborateur')], default='collaborateur', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InviteCode',
        ),
    ]
