# Generated by Django 5.2.17 on 2026-09-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_mfa_verified',
            field=models.BooleanField(default=False),
        ),
    ]
