# Generated by Django 5.2.17 on 2026-09-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_session_mfa_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_last_counter',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_pending_secret',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_recovery_hashes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.TextField(blank=True),
        ),
    ]
