# Generated by Django 5.2.17 on 2026-09-23 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_task_overdue_notified_at_task_reminder_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_status',
            field=models.CharField(blank=True, choices=[('', 'Aucun e-mail'), ('en_attente', "En attente d'envoi"), ('envoyé', 'Envoyé'), ('échec', 'Échec définitif')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='notification',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='next_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(choices=[('info', 'Information'), ('attention', 'Attention'), ('haute', 'Haute'), ('critique', 'Critique')], default='info', max_length=12),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('manuelle', 'Créée par un utilisateur'), ('automatique', 'Créée par la GED')], default='manuelle', max_length=12),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['email_status', 'next_email_at'], name='notif_email_idx'),
        ),
    ]
