# Generated by Codex on 2026-09-01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("success", "Réussie"), ("failure", "Échouée")], max_length=16)),
                ("checked_documents", models.PositiveIntegerField(default=0)),
                ("checked_bytes", models.PositiveBigIntegerField(default=0)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("requested_by", models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name="backup_runs", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
