# Generated by Django 5.2.17 on 2026-09-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_backup_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprun',
            name='pruned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
