# Generated by Django 5.2.17 on 2026-08-31 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('objet', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(default='ouvert', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dossiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
