# Generated by Django 5.2.17 on 2026-09-23 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_ocr_attempts_document_ocr_next_retry_at_and_more'),
        ('dossiers', '0006_party_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossierchecklistitem',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='documents.document'),
        ),
        migrations.AddField(
            model_name='dossierchecklistitem',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossierchecklistitem',
            name='reminder_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossierchecklistitem',
            name='source',
            field=models.CharField(choices=[('manuel', 'Ajouté à la main'), ('modele', 'Généré depuis le modèle')], default='manuel', max_length=8),
        ),
        migrations.AddField(
            model_name='dossierchecklistitem',
            name='type_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(choices=[('IMM', 'Immobilier'), ('FON', 'Foncier'), ('SUC', 'Succession'), ('DON', 'Donation'), ('FAM', 'Famille'), ('MAT', 'Régime matrimonial'), ('TES', 'Testament'), ('SOC', 'Société'), ('ENT', 'Entreprise'), ('HYP', 'Hypothèque / garantie'), ('PRO', 'Procuration'), ('PAT', 'Patrimoine'), ('IND', 'Indivision'), ('PAR', 'Partage'), ('VEN', 'Vente'), ('BAI', 'Bail'), ('CRE', 'Créance / garantie'), ('DIV', 'Divorce / liquidation patrimoniale'), ('AUT', 'Autres actes')], max_length=4)),
                ('label', models.CharField(max_length=255)),
                ('type_code', models.CharField(blank=True, max_length=6)),
                ('required', models.BooleanField(default=True)),
                ('reminder_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domaine', 'order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('domaine', 'label'), name='unique_modele_checklist')],
            },
        ),
        migrations.AddField(
            model_name='dossierchecklistitem',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='dossiers.checklisttemplate'),
        ),
        migrations.AddConstraint(
            model_name='dossierchecklistitem',
            constraint=models.UniqueConstraint(fields=('dossier', 'template'), name='unique_item_par_modele'),
        ),
    ]
