# Generated by Django 5.2.17 on 2026-08-31 16:12

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('code_notarial', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to=documents.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('extracted_text', models.TextField(blank=True)),
                ('niveau_de_confidentialite', models.CharField(choices=[('Standard', 'Standard'), ('Restreint', 'Restreint'), ('Confidentiel', 'Confidentiel')], default='Standard', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente_validation', 'En attente de validation'), ('validé', 'Validé'), ('archivé', 'Archivé'), ('rejeté', 'Rejeté')], default='brouillon', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='dossiers.dossier')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type', 'niveau_de_confidentialite'], name='documents_d_type_372ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['reference'], name='documents_d_referen_a458fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'document'), name='unique_user_document_favorite'),
        ),
    ]
