# Generated by Django 6.1.1 on 2026-09-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_destruction_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='statut',
            field=models.CharField(choices=[('à_indexer', 'À indexer'), ('brouillon', 'Brouillon'), ('à_contrôler', 'À contrôler'), ('en_validation', 'En validation'), ('validé', 'Validé'), ('clos', 'Clos'), ('archivé', 'Archivé'), ('rejeté', 'Rejeté'), ('à_corriger', 'À corriger'), ('annulé', 'Annulé'), ('corbeille', 'Corbeille'), ('destruction_demandée', 'Destruction demandée'), ('destruction_autorisée', 'Destruction autorisée'), ('détruit', 'Détruit')], default='à_indexer', max_length=32),
        ),
    ]
