# Generated by Django 5.2.17 on 2026-09-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='statut_avant_corbeille',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
