# Generated by Django 5.2.17 on 2026-09-21 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_statut_avant_corbeille'),
        ('dossiers', '0006_party_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='documents_d_created_71dced_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['statut'], name='documents_d_statut_ca88e6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_archived', 'is_current', 'trashed_at'], name='doc_liste_courante_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['dossier', 'is_current'], name='doc_par_dossier_idx'),
        ),
    ]
