# Generated by Django 5.2.17 on 2026-09-23 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_documents_d_created_71dced_idx_and_more'),
        ('dossiers', '0006_party_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('extrait', 'Extrait'), ('indisponible', 'Indisponible'), ('échec', 'Échec')], default='en_attente', max_length=16),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['ocr_status', 'ocr_next_retry_at'], name='doc_file_ocr_idx'),
        ),
    ]
