# Generated by Django 5.2.17 on 2026-09-23 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditlog_audit_audit_timesta_901180_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('dedup_key', models.CharField(max_length=190, unique=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ouverte', 'Ouverte'), ('traitée', 'Traitée')], default='ouverte', max_length=10)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handling_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_security_alerts', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='alerte_statut_idx')],
            },
        ),
    ]
