# Generated by Django 5.2.17 on 2026-09-23 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=190, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, unique=True)),
                ('holder', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=120, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('host', models.CharField(blank=True, max_length=120)),
                ('pid', models.PositiveIntegerField(default=0)),
                ('groups', models.CharField(blank=True, max_length=120)),
                ('last_seen', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('demandé', 'Demandé'), ('en_cours', 'En cours'), ('succès', 'Réussi'), ('échec', 'Échoué')], default='en_cours', max_length=16)),
                ('trigger', models.CharField(choices=[('planifié', 'Planifié'), ('manuel', "Demandé depuis l'écran"), ('commande', 'Ligne de commande')], default='planifié', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('items', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('host', models.CharField(blank=True, max_length=120)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['name', '-requested_at'], name='jobrun_nom_idx'), models.Index(fields=['status'], name='jobrun_statut_idx')],
            },
        ),
    ]
